[project]
name = "NotSteam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "convex>=0.7.0",
    "python-dotenv>=1.1.1",
]
